language: go

go:
- 1.8

install:
  - go get -v -t .
  - go get -v github.com/mattn/goveralls
  - go install -v github.com/mattn/goveralls

script:
  - go test -covermode count -coverprofile cover.out
  - go test -test.run Benchmark -cpu 1 -bench .

branches:
  only:
    - develop
    - gh-pages
    - /.*/

notifications:
  email: change

